# Generated by Django 2.1.3 on 2018-12-04 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentColorState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('power', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SavedColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('red', models.PositiveSmallIntegerField()),
                ('green', models.PositiveSmallIntegerField()),
                ('blue', models.PositiveSmallIntegerField()),
                ('brightness', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledColorChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('effect', models.CharField(choices=[('UC', 'Update Color'), ('TC', 'Temporarily Update Color'), ('BE', 'Breathe Effect')], default='UC', max_length=2)),
                ('state', models.CharField(choices=[('NS', 'Not Started'), ('RN', 'Running'), ('CP', 'Complete')], default='NS', max_length=2)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='ColorApp.SavedColor')),
            ],
        ),
        migrations.AddField(
            model_name='currentcolorstate',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='ColorApp.SavedColor'),
        ),
    ]
