# Generated by Django 2.1.3 on 2018-12-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentcolorstate',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='savedcolor',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
